### ISSUE TITLE
Multiple Roles at Multiple Schools/Locations/Websites

### ISSUE THREAD

**Issue by suzannezc** [wrdsb/wordpress-plugin-staff-list#25]
So, some people have multiple different roles, one per location. For instance:

.25 FTE secretary school a
.5 FTE library clerk school b

Suggested temporary fix: make "Support Staff" role for those who are in multiple support staff roles in multiple locations. 

Longer term fix: create a little bit more in the profile

You are a member of these sites. Please choose your role per site:

School A: secretary
School B: library clerk
School C: lunch lady

et cetera...

Brought to us by the fantabulous Heidi.

**Comment by jschumann** [comment]
We're going to change the user metadata to be site-specific options, rather than stored as fields in their global profile.
